# Generated by Django 3.2.9 on 2021-11-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('slug', models.SlugField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('Q', 'Question'), ('C', 'Complaint')], max_length=100)),
                ('text', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
